In [14]:
import pandas as pd
import numpy as np
import cx_Oracle
from sqlalchemy import create_engine

import dash
import dash_table
import dash_html_components as html
import dash_core_components as dcc
from dash.dependencies import Input, Output, State

In [3]:
conn = create_engine('oracle://c##big:1234@localhost:1521/orcl')

In [8]:
df = pd.read_sql_query('''select * from all_tab_cols where owner = 'C##BIG'  ''',con=conn)

In [17]:
df.loc[df.table_name == 'TITANIC_MASTER',"column_name"]

0     PASSENGERS
1    PASSENGERID
Name: column_name, dtype: object

In [35]:
app = dash.Dash('__name__')
app.layout = html.Div(
    [
        dcc.Dropdown(
            id = 'my-dropdown',
            options = [{'label':i,'value':i} for i in df.table_name.unique()]
        ),
        html.Hr(),
        html.Br(),
        dash_table.DataTable(
            id = 'my-table',
            page_size = 6,
            style_cell={'minWidth': 95, 'maxWidth': 95, 'width': 9}
        )
    ]
)

In [36]:
@app.callback(
    Output('my-table','columns'),
    Output('my-table','data'),
    Input('my-dropdown','value')
)
def update_table(table_name):
    columns =[{'name':i.lower(),'id':i.lower()} for i in df.loc[df.table_name == table_name,"column_name"]]
    stmt = 'select * from {}'.format(table_name)
    table_df = pd.read_sql_query(stmt,con=conn)
    data = table_df.to_dict('records')
    return columns, data

In [37]:
app.run_server(host='192.168.0.7',port='7777')

Dash is running on http://192.168.0.7:7777/

Dash is running on http://192.168.0.7:7777/

Dash is running on http://192.168.0.7:7777/

Dash is running on http://192.168.0.7:7777/

Dash is running on http://192.168.0.7:7777/

Dash is running on http://192.168.0.7:7777/

Dash is running on http://192.168.0.7:7777/

Dash is running on http://192.168.0.7:7777/

INFO:__name__:Dash is running on http://192.168.0.7:7777/

 * Serving Flask app "__name__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

INFO:werkzeug: * Running on http://192.168.0.7:7777/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.0.7 - - [20/May/2021 16:07:23] "GET / HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.7 - - [20/May/2021 16:07:23] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.7 - - [20/May/2021 16:07:23] "GET /_dash-dependencies HTTP/1.1" 200 -

Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-00942: 테이블 또는 뷰가 존재하지 않습니다

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\Anaconda3\lib\site-packages\dash\dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\Users\admin\Anaconda3\lib\site-packages\dash\dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-36-72df114b7ae4>", line 9, in update_table
    table_df = pd.read_sql_query(stmt,con=conn)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 332, in read_sql_query
    chunksize=chunksize,
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1218, in read_query
    result = self.execute(*args)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1087, in execute
    return self.connectable.execute(*args, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2179, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1155, in _execute_text
    parameters,
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00942: 테이블 또는 뷰가 존재하지 않습니다
[SQL: select * from None]
(Background on this error at: http://sqlalche.me/e/4xp6)
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-00942: 테이블 또는 뷰가 존재하지 않습니다

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\Anaconda3\lib\site-packages\dash\dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\Users\admin\Anaconda3\lib\site-packages\dash\dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-36-72df114b7ae4>", line 9, in update_table
    table_df = pd.read_sql_query(stmt,con=conn)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 332, in read_sql_query
    chunksize=chunksize,
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1218, in read_query
    result = self.execute(*args)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1087, in execute
    return self.connectable.execute(*args, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2179, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1155, in _execute_text
    parameters,
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00942: 테이블 또는 뷰가 존재하지 않습니다
[SQL: select * from None]
(Background on this error at: http://sqlalche.me/e/4xp6)
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-00942: 테이블 또는 뷰가 존재하지 않습니다

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\Anaconda3\lib\site-packages\dash\dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\Users\admin\Anaconda3\lib\site-packages\dash\dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-36-72df114b7ae4>", line 9, in update_table
    table_df = pd.read_sql_query(stmt,con=conn)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 332, in read_sql_query
    chunksize=chunksize,
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1218, in read_query
    result = self.execute(*args)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1087, in execute
    return self.connectable.execute(*args, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2179, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1155, in _execute_text
    parameters,
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00942: 테이블 또는 뷰가 존재하지 않습니다
[SQL: select * from None]
(Background on this error at: http://sqlalche.me/e/4xp6)
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-00942: 테이블 또는 뷰가 존재하지 않습니다

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\Anaconda3\lib\site-packages\dash\dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\Users\admin\Anaconda3\lib\site-packages\dash\dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-36-72df114b7ae4>", line 9, in update_table
    table_df = pd.read_sql_query(stmt,con=conn)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 332, in read_sql_query
    chunksize=chunksize,
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1218, in read_query
    result = self.execute(*args)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1087, in execute
    return self.connectable.execute(*args, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2179, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1155, in _execute_text
    parameters,
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00942: 테이블 또는 뷰가 존재하지 않습니다
[SQL: select * from None]
(Background on this error at: http://sqlalche.me/e/4xp6)
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-00942: 테이블 또는 뷰가 존재하지 않습니다

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\Anaconda3\lib\site-packages\dash\dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\Users\admin\Anaconda3\lib\site-packages\dash\dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-36-72df114b7ae4>", line 9, in update_table
    table_df = pd.read_sql_query(stmt,con=conn)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 332, in read_sql_query
    chunksize=chunksize,
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1218, in read_query
    result = self.execute(*args)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1087, in execute
    return self.connectable.execute(*args, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2179, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1155, in _execute_text
    parameters,
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00942: 테이블 또는 뷰가 존재하지 않습니다
[SQL: select * from None]
(Background on this error at: http://sqlalche.me/e/4xp6)
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-00942: 테이블 또는 뷰가 존재하지 않습니다

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request

ERROR:__name__:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-00942: 테이블 또는 뷰가 존재하지 않습니다

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\admin\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\admin\Anaconda3\lib\site-packages\dash\dash.py", line 1078, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\Users\admin\Anaconda3\lib\site-packages\dash\dash.py", line 1009, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "<ipython-input-36-72df114b7ae4>", line 9, in update_table
    table_df = pd.read_sql_query(stmt,con=conn)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 332, in read_sql_query
    chunksize=chunksize,
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1218, in read_query
    result = self.execute(*args)
  File "C:\Users\admin\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1087, in execute
    return self.connectable.execute(*args, **kwargs)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2179, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1155, in _execute_text
    parameters,
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\admin\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00942: 테이블 또는 뷰가 존재하지 않습니다
[SQL: select * from None]
(Background on this error at: http://sqlalche.me/e/4xp6)
INFO:werkzeug:192.168.0.7 - - [20/May/2021 16:07:23] "POST /_dash-update-component HTTP/1.1" 500 -
INFO:werkzeug:192.168.0.7 - - [20/May/2021 16:07:25] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.7 - - [20/May/2021 16:07:32] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.7 - - [20/May/2021 16:07:35] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.7 - - [20/May/2021 16:07:40] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:192.168.0.7 - - [20/May/2021 16:07:43] "POST /_dash-update-component HTTP/1.1" 200 -