In [10]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [5]:
data = load_iris()

In [7]:
df = pd.DataFrame(data['data'])
df.columns = data['feature_names']
df['target'] = data['target']

In [11]:
df['Species'] = np.where(df.target == 0,'setosa',\
                         np.where(df.target == 1,'versicolor','verginica'))

In [13]:
df.drop('target',axis=1,inplace=True)

In [14]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,verginica
146,6.3,2.5,5.0,1.9,verginica
147,6.5,3.0,5.2,2.0,verginica
148,6.2,3.4,5.4,2.3,verginica
149,5.9,3.0,5.1,1.8,verginica

In [17]:
type("1.")

str

In [20]:
np.array([12],dtype='int8').dtype

dtype('int8')

In [22]:
df.iloc[:,1].max()

4.4

In [29]:
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),Species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,verginica
146,6.3,2.5,5.0,1.9,verginica
147,6.5,3.0,5.2,2.0,verginica
148,6.2,3.4,5.4,2.3,verginica
149,5.9,3.0,5.1,1.8,verginica

In [42]:
x = []
a = 0
for i in range(len(df.Species)):
    x = list(df.iloc[i,:].values)
    x.insert(a,a+1)
    x.append(('insert into iris(sl,sw,pl,pw,sp) values',))

In [55]:
x = list(df.iloc[0,:].values)
x.insert(0,0)
x

[0, 5.1, 3.5, 1.4, 0.2, 'setosa']

In [52]:
x.insert(0,0)
tuple(x)

(0, 0, 4.9, 3.0, 1.4, 0.2, 'setosa')

In [58]:
a = 1
for i in range(len(df.Species)):
    x = list(df.iloc[i,:].values)
    x.insert(0,a)
    x = tuple(x)
    print('insert into iris(seq, sl,sw,pl,pw,sp) values',x,';')
    a += 1

insert into iris(seq, sl,sw,pl,pw,sp) values (1, 5.1, 3.5, 1.4, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (2, 4.9, 3.0, 1.4, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (3, 4.7, 3.2, 1.3, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (4, 4.6, 3.1, 1.5, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (5, 5.0, 3.6, 1.4, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (6, 5.4, 3.9, 1.7, 0.4, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (7, 4.6, 3.4, 1.4, 0.3, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (8, 5.0, 3.4, 1.5, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (9, 4.4, 2.9, 1.4, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (10, 4.9, 3.1, 1.5, 0.1, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (11, 5.4, 3.7, 1.5, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (12, 4.8, 3.4, 1.6, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (13, 4.8, 3.0, 1.4, 0.1, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (14, 4.3, 3.0, 1.1, 0.1, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (15, 5.8, 4.0, 1.2, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (16, 5.7, 4.4, 1.5, 0.4, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (17, 5.4, 3.9, 1.3, 0.4, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (18, 5.1, 3.5, 1.4, 0.3, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (19, 5.7, 3.8, 1.7, 0.3, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (20, 5.1, 3.8, 1.5, 0.3, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (21, 5.4, 3.4, 1.7, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (22, 5.1, 3.7, 1.5, 0.4, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (23, 4.6, 3.6, 1.0, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (24, 5.1, 3.3, 1.7, 0.5, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (25, 4.8, 3.4, 1.9, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (26, 5.0, 3.0, 1.6, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (27, 5.0, 3.4, 1.6, 0.4, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (28, 5.2, 3.5, 1.5, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (29, 5.2, 3.4, 1.4, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (30, 4.7, 3.2, 1.6, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (31, 4.8, 3.1, 1.6, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (32, 5.4, 3.4, 1.5, 0.4, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (33, 5.2, 4.1, 1.5, 0.1, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (34, 5.5, 4.2, 1.4, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (35, 4.9, 3.1, 1.5, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (36, 5.0, 3.2, 1.2, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (37, 5.5, 3.5, 1.3, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (38, 4.9, 3.6, 1.4, 0.1, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (39, 4.4, 3.0, 1.3, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (40, 5.1, 3.4, 1.5, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (41, 5.0, 3.5, 1.3, 0.3, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (42, 4.5, 2.3, 1.3, 0.3, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (43, 4.4, 3.2, 1.3, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (44, 5.0, 3.5, 1.6, 0.6, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (45, 5.1, 3.8, 1.9, 0.4, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (46, 4.8, 3.0, 1.4, 0.3, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (47, 5.1, 3.8, 1.6, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (48, 4.6, 3.2, 1.4, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (49, 5.3, 3.7, 1.5, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (50, 5.0, 3.3, 1.4, 0.2, 'setosa') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (51, 7.0, 3.2, 4.7, 1.4, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (52, 6.4, 3.2, 4.5, 1.5, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (53, 6.9, 3.1, 4.9, 1.5, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (54, 5.5, 2.3, 4.0, 1.3, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (55, 6.5, 2.8, 4.6, 1.5, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (56, 5.7, 2.8, 4.5, 1.3, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (57, 6.3, 3.3, 4.7, 1.6, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (58, 4.9, 2.4, 3.3, 1.0, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (59, 6.6, 2.9, 4.6, 1.3, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (60, 5.2, 2.7, 3.9, 1.4, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (61, 5.0, 2.0, 3.5, 1.0, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (62, 5.9, 3.0, 4.2, 1.5, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (63, 6.0, 2.2, 4.0, 1.0, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (64, 6.1, 2.9, 4.7, 1.4, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (65, 5.6, 2.9, 3.6, 1.3, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (66, 6.7, 3.1, 4.4, 1.4, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (67, 5.6, 3.0, 4.5, 1.5, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (68, 5.8, 2.7, 4.1, 1.0, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (69, 6.2, 2.2, 4.5, 1.5, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (70, 5.6, 2.5, 3.9, 1.1, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (71, 5.9, 3.2, 4.8, 1.8, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (72, 6.1, 2.8, 4.0, 1.3, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (73, 6.3, 2.5, 4.9, 1.5, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (74, 6.1, 2.8, 4.7, 1.2, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (75, 6.4, 2.9, 4.3, 1.3, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (76, 6.6, 3.0, 4.4, 1.4, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (77, 6.8, 2.8, 4.8, 1.4, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (78, 6.7, 3.0, 5.0, 1.7, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (79, 6.0, 2.9, 4.5, 1.5, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (80, 5.7, 2.6, 3.5, 1.0, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (81, 5.5, 2.4, 3.8, 1.1, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (82, 5.5, 2.4, 3.7, 1.0, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (83, 5.8, 2.7, 3.9, 1.2, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (84, 6.0, 2.7, 5.1, 1.6, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (85, 5.4, 3.0, 4.5, 1.5, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (86, 6.0, 3.4, 4.5, 1.6, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (87, 6.7, 3.1, 4.7, 1.5, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (88, 6.3, 2.3, 4.4, 1.3, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (89, 5.6, 3.0, 4.1, 1.3, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (90, 5.5, 2.5, 4.0, 1.3, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (91, 5.5, 2.6, 4.4, 1.2, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (92, 6.1, 3.0, 4.6, 1.4, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (93, 5.8, 2.6, 4.0, 1.2, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (94, 5.0, 2.3, 3.3, 1.0, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (95, 5.6, 2.7, 4.2, 1.3, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (96, 5.7, 3.0, 4.2, 1.2, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (97, 5.7, 2.9, 4.2, 1.3, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (98, 6.2, 2.9, 4.3, 1.3, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (99, 5.1, 2.5, 3.0, 1.1, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (100, 5.7, 2.8, 4.1, 1.3, 'versicolor') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (101, 6.3, 3.3, 6.0, 2.5, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (102, 5.8, 2.7, 5.1, 1.9, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (103, 7.1, 3.0, 5.9, 2.1, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (104, 6.3, 2.9, 5.6, 1.8, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (105, 6.5, 3.0, 5.8, 2.2, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (106, 7.6, 3.0, 6.6, 2.1, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (107, 4.9, 2.5, 4.5, 1.7, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (108, 7.3, 2.9, 6.3, 1.8, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (109, 6.7, 2.5, 5.8, 1.8, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (110, 7.2, 3.6, 6.1, 2.5, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (111, 6.5, 3.2, 5.1, 2.0, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (112, 6.4, 2.7, 5.3, 1.9, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (113, 6.8, 3.0, 5.5, 2.1, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (114, 5.7, 2.5, 5.0, 2.0, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (115, 5.8, 2.8, 5.1, 2.4, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (116, 6.4, 3.2, 5.3, 2.3, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (117, 6.5, 3.0, 5.5, 1.8, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (118, 7.7, 3.8, 6.7, 2.2, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (119, 7.7, 2.6, 6.9, 2.3, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (120, 6.0, 2.2, 5.0, 1.5, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (121, 6.9, 3.2, 5.7, 2.3, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (122, 5.6, 2.8, 4.9, 2.0, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (123, 7.7, 2.8, 6.7, 2.0, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (124, 6.3, 2.7, 4.9, 1.8, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (125, 6.7, 3.3, 5.7, 2.1, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (126, 7.2, 3.2, 6.0, 1.8, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (127, 6.2, 2.8, 4.8, 1.8, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (128, 6.1, 3.0, 4.9, 1.8, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (129, 6.4, 2.8, 5.6, 2.1, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (130, 7.2, 3.0, 5.8, 1.6, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (131, 7.4, 2.8, 6.1, 1.9, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (132, 7.9, 3.8, 6.4, 2.0, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (133, 6.4, 2.8, 5.6, 2.2, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (134, 6.3, 2.8, 5.1, 1.5, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (135, 6.1, 2.6, 5.6, 1.4, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (136, 7.7, 3.0, 6.1, 2.3, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (137, 6.3, 3.4, 5.6, 2.4, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (138, 6.4, 3.1, 5.5, 1.8, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (139, 6.0, 3.0, 4.8, 1.8, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (140, 6.9, 3.1, 5.4, 2.1, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (141, 6.7, 3.1, 5.6, 2.4, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (142, 6.9, 3.1, 5.1, 2.3, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (143, 5.8, 2.7, 5.1, 1.9, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (144, 6.8, 3.2, 5.9, 2.3, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (145, 6.7, 3.3, 5.7, 2.5, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (146, 6.7, 3.0, 5.2, 2.3, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (147, 6.3, 2.5, 5.0, 1.9, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (148, 6.5, 3.0, 5.2, 2.0, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (149, 6.2, 3.4, 5.4, 2.3, 'verginica') ;
insert into iris(seq, sl,sw,pl,pw,sp) values (150, 5.9, 3.0, 5.1, 1.8, 'verginica') ;