# **연습**

In [1]:
from bs4 import BeautifulSoup
from selenium import webdriver
chrome_loc = 'C:/chrome/chromedriver.exe'
driver = webdriver.Chrome(chrome_loc)
url_target = 'https://kr.investing.com/equities/south-korea'
driver.get(url_target)

In [3]:
invest_html = driver.page_source
soup = BeautifulSoup(invest_html, 'html.parser')
title2 = soup.select('td')   ## 나머지 뽑기위함

In [4]:
[j.text for j in title2][1:8]

['KB금융', '57,700', '58,300', '57,700', '-300', '-0.52%', '265.81K']

In [5]:
name = []
now = []
high = []
low = []
delta = []
delta_p = []
count = []
for i in range(50):
    name.append([j.text for j in title2][1 + i*10])
    now.append([j.text for j in title2][2 + i*10])
    high.append([j.text for j in title2][3 + i*10])
    low.append([j.text for j in title2][4 + i*10])
    delta.append([j.text for j in title2][5 + i*10])
    delta_p.append([j.text for j in title2][6 + i*10])
    count.append([j.text for j in title2][7 + i*10])

In [6]:
import pandas as pd
investing = pd.DataFrame()
investing['종목'] = name
investing['현재가'] = now
investing['고가'] = high
investing['저가'] = low
investing['변동'] = delta
investing['변동 %'] = delta_p
investing['거래량'] = count
investing.index = range(1,51)

In [7]:
investing

          종목         현재가          고가          저가        변동    변동 %      거래량
1       KB금융      57,700      58,300      57,700      -300  -0.52%  265.81K
2         KT      33,500      33,750      33,100      +300  +0.90%  428.44K
3       KT&G      85,100      85,100      84,600      +600  +0.71%  243.51K
4         LG      99,700     100,000      99,400      -200  -0.20%  147.29K
5    LG디스플레이      23,550      23,950      23,250      -150  -0.63%    1.28M
6     LG생활건강   1,535,000   1,535,000   1,525,000         0   0.00%    6.31K
7     LG유플러스      15,450      15,600      15,400       +50  +0.32%  584.65K
8       LG전자     154,000     156,000     154,000     -1000  -0.65%  268.74K
9       LG화학     810,000     814,000     807,000     -4000  -0.49%   72.91K
10     S-oil     101,500     103,000     100,500     -1000  -0.98%  101.14K
11  SK 바이오팜   118,000.00  120,000.00  114,000.00  +4000.00  +3.51%  653.86K
12      SK그룹     269,500     271,500     269,000     -1500  -0.55%   48.70K
13   SK이노베이션     271,000     275,000     270,000     -3500  -1.28%  163.52K
14     SK텔레콤     326,500     329,000     324,000     +3000  +0.93%  139.57K
15    SK하이닉스     127,500     127,500     125,000     -1000  -0.78%    2.62M
16      강원랜드      28,650      29,200      28,400      +100  +0.35%  508.62K
17      고려아연     436,500     437,500     434,000         0   0.00%   11.98K
18       기아차      91,400      91,400      88,600     +1400  +1.56%    2.02M
19      기업은행      11,000      11,100      10,900         0   0.00%  843.81K
20  네이버 주식회사     364,000     365,500     361,500     +1500  +0.41%  177.33K
21       넷마블     141,000     143,000     140,000     +1000  +0.71%  155.02K
22     롯데케미칼     276,000     282,000     276,000     -5500  -1.95%  147.89K
23     삼성SDI     619,000     622,000     616,000     -3000  -0.48%   54.50K
24      삼성물산     142,000     143,500     141,000      +500  +0.35%  154.93K
25  삼성바이오로직스     873,000     881,000     860,000    +31000  +3.68%  171.39K
26      삼성생명      83,900      84,400      83,300      +200  +0.24%  123.75K
27   삼성에스디에스     189,000     190,000     187,000      +500  +0.27%   55.41K
28      삼성전기     177,000     179,500     176,000     -3000  -1.67%  202.19K
29      삼성전자      82,200      82,600      81,800      +300  +0.37%    7.17M
30  삼성화재해상보험     217,500     218,500     216,000      +500  +0.23%   32.20K
31      셀트리온     269,000     269,500     265,000     +4500  +1.70%  265.46K
32      신한지주      42,700      42,900      42,550      -200  -0.47%  426.35K
33      아모레G      78,000      78,000      76,700     +1000  +1.30%   57.92K
34    아모레퍼시픽     275,500     278,000     272,000     +1500  +0.55%   37.72K
35     엔씨소프트     848,000     853,000     841,000     +5000  +0.59%   18.41K
36    우리금융지주      11,700      11,750      11,650       +50  +0.43%  637.41K
37       이마트     160,000     160,500     159,000         0   0.00%   46.13K
38       카카오     128,000     128,500     126,500     +2000  +1.59%    1.13M
39       코웨이      79,000      80,400      78,700      -800  -1.00%  109.07K
40       포스코     337,500     341,000     333,000     -2000  -0.59%  266.74K
41    하나금융지주      47,050      47,250      46,700       -50  -0.11%  365.23K
42       하이브     264,500     267,000     263,500     -1000  -0.38%   66.50K
43      한국전력      26,700      27,150      26,400      -450  -1.66%    3.82M
44    한국조선해양     141,000     143,000     140,500     -2000  -1.40%  146.46K
45     한국타이어      55,000      55,300      53,200     +1300  +2.42%  246.29K
46     한온시스템      17,350      17,400      17,050         0   0.00%  383.14K
47      현대건설      58,500      59,000      56,200     +2200  +3.91%    1.38M
48    현대글로비스     199,000     199,500     191,500     +5000  +2.58%  139.97K
49     현대모비스     288,000     288,500     284,000     +2500  +0.88%  168.84K
50       현대차     244,000     244,500     238,500     +2500  +1.04%  479.01K